CREATE TABLE regionals
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regional_id BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    active      BOOLEAN      NOT NULL,
    updated_at  TIMESTAMP
);