CREATE TABLE regionals
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_regionals_external_active ON regionals (external_id, active);